import { Flavor } from '../../models/flavor';

export const Flavors: Flavor[] = [
    { flavor: 'Iris' },
    { flavor: 'Peony' },
    { flavor: 'Elderflower' },
    { flavor: 'Acacia' },
    { flavor: 'Lilac' },
    { flavor: 'Jasmine' },
    { flavor: 'Honeysuckle' },
    { flavor: 'Violet' },
    { flavor: 'Lavender' },
    { flavor: 'Rose' },
    { flavor: 'Potpourri' },
    { flavor: 'Hibiscus' },
    { flavor: 'Lime' },
    { flavor: 'Lemon' },
    { flavor: 'Grapefruit' },
    { flavor: 'Orange' },
    { flavor: 'Marmalade' },
    { flavor: 'Quince' },
    { flavor: 'Apple' },
    { flavor: 'Pear' },
    { flavor: 'Nectarine' },
    { flavor: 'Peach' },
    { flavor: 'Apricot' },
    { flavor: 'Persimmon' },
    { flavor: 'Pineapple' },
    { flavor: 'Mango' },
    { flavor: 'Guava' },
    { flavor: 'Passion Fruit' },
    { flavor: 'Lychee' },
    { flavor: 'Bubblegum' },
    { flavor: 'Cranberry' },
    { flavor: 'Red Plum' },
    { flavor: 'Pomegranate' },
    { flavor: 'Sour Cherry' },
    { flavor: 'Strawberry' },
    { flavor: 'Cherry' },
    { flavor: 'Raspberry' },
    { flavor: 'Boysenberry' },
    { flavor: 'Black Currant' },
    { flavor: 'Black Cherry' },
    { flavor: 'Plum' },
    { flavor: 'Blackberry' },
    { flavor: 'Blueberry' },
    { flavor: 'Olive' },
    { flavor: 'Raisin' },
    { flavor: 'Fig' },
    { flavor: 'Date' },
    { flavor: 'Fruitcake' },
    { flavor: 'Beeswax' },
    { flavor: 'Ginger' },
    { flavor: 'Honey' },
    { flavor: 'White Pepper' },
    { flavor: 'Red Pepper' },
    { flavor: 'Black Pepper' },
    { flavor: 'Cinnamon' },
    { flavor: 'Anise' },
    { flavor: '5-Spice' },
    { flavor: 'Fennel' },
    { flavor: 'Eucalyptus' },
    { flavor: 'Mint' },
    { flavor: 'Thyme' },
    { flavor: 'Grass' },
    { flavor: 'Tomato Leaf' },
    { flavor: 'Gooseberry' },
    { flavor: 'Bell Pepper' },
    { flavor: 'Jalapeño' },
    { flavor: 'Bitter Almond' },
    { flavor: 'Tomato' },
    { flavor: 'Sun-Dried Tomato' },
    { flavor: 'Black Tea' },
    { flavor: 'Clay Pot' },
    { flavor: 'Slate' },
    { flavor: 'Pencil Shavings' },
    { flavor: 'Wet Gravel' },
    { flavor: 'Potting Soil' },
    { flavor: 'Red Beet' },
    { flavor: 'Volcanic Rocks' },
    { flavor: 'Petroleum' },
    { flavor: 'Butter' },
    { flavor: 'Cream' },
    { flavor: 'Sourdough' },
    { flavor: 'Lager' },
    { flavor: 'Truffle' },
    { flavor: 'Mushroom' },
    { flavor: 'Vanilla' },
    { flavor: 'Coconut' },
    { flavor: 'Baking Spices' },
    { flavor: 'Cigar Box' },
    { flavor: 'Smoke' },
    { flavor: 'Dill' },
    { flavor: 'Dried Fruit' },
    { flavor: 'Nutty Flavors' },
    { flavor: 'Tobacco' },
    { flavor: 'Coffee' },
    { flavor: 'Cocoa' },
    { flavor: 'Leather' },
    { flavor: 'Musty Cardboard' },
    { flavor: 'Wet Dog' },
    { flavor: 'Cured Meat' },
    { flavor: 'Boiled Eggs' },
    { flavor: 'Burnt Rubber' },
    { flavor: 'Lit Match' },
    { flavor: 'Garlic' },
    { flavor: 'Onion' },
    { flavor: 'Cat Pee' },
    { flavor: 'Black Cardamon' },
    { flavor: 'Band-Aid' },
    { flavor: 'Sweaty Leather Saddle' },
    { flavor: 'Horse Manure' },
    { flavor: 'Toffee' },
    { flavor: 'Stewed Fruit' },
    { flavor: 'Vinegar' },
    { flavor: 'Nail Polish Remover' }
]